name: Deploy Vue to EC2 (manual)

on:
  workflow_dispatch:
    inputs:
        version:
            description: 'version'
            required: false
            default: 'latest'
            type: string
        command:
            description: 'deploy'
            required: true
            default: 'deploy'
            type: choice
            options:
                - deploy2docker
                - deploy2cluster

jobs:
  build:
    if: ${{ github.event.inputs.command == 'deploy2cluster' }} 
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: login to dockerhub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: build docker image
        run: |
          docker build -t "${DOCKER_HUB_USERNAME}/ceramicraft-customer-frontend:${{ github.event.inputs.version }}" .
      - name: push to dockerhub
        run: |
          docker push "${DOCKER_HUB_USERNAME}/ceramicraft-customer-frontend:${{ github.event.inputs.version }}"

  cluster-deploy:
    if : ${{ github.event.inputs.command == 'deploy2cluster'}}
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      YAML_FILE: vue_apps/overlays/customer_frontend/patch.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: NUS-ISS-Agile-Team/ceramicraft-argocd-deploy.git
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops
          ref: main
      - name: update YAML file
        run: |
          sed -i "s|image: .*$|image: ${DOCKER_HUB_USERNAME}/ceramicraft-customer-frontend:${{ github.event.inputs.version }}|g" gitops/${YAML_FILE}
      - name: Commit and Push changes
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ${YAML_FILE}
          git commit -m "chore: update customer-frontend image to ${{ github.event.inputs.version }}" || exit 0
          git push 
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install & Build
        run: |
          npm ci
          npm run build
      - name: Add SSH key
        env: 
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Push dist to server
        run: |
          rsync -avz --delete --exclude=.git \
            dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}/
      - name: Reload Nginx
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker exec nginx nginx -s reload"